[global]
domain=forsetijudge.com
tls=true
telemetry=true

[session]
expiration=6h
root_expiration=30m
system_expiration=10m

[alloy]
ratelimit_average=100
ratelimit_burst=200
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[api]
replicas=1
ratelimit_average=100
ratelimit_burst=200
cpus="1.0"
memory_limit=1G
cpus_reservation="0.5"
memory_reservation=512M

[autojudge]
max_concurrent_submissions=1
cpus="1.0"
memory_limit=1G
cpus_reservation="0.5"
memory_reservation=512M

[autojudge_autoscaler]
cooldown=60
interval=10
messages_per_replica=5
max_replicas=3
min_replicas=1
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[cadvisor]
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[clamav]
cpus="1.0"
memory_limit=2G
cpus_reservation="0.5"
memory_reservation=1G

[grafana]
ratelimit_average=100
ratelimit_burst=200
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M

[loki]
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M

[migration]
cpus="0.2"
memory_limit=256M
cpus_reservation="0.1"
memory_reservation=128M

[minio]
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M

[minio_init]
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[node_exporter]
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[postgres]
cpus="1.0"
memory_limit=1G
cpus_reservation="0.5"
memory_reservation=512M

[postgres_exporter]
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[prometheus]
ratelimit_average=100
ratelimit_burst=200
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M

[rabbitmq]
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M

[redis]
maxmemory=400mb
cpus="0.2"
memory_limit=256M
cpus_reservation="0.1"
memory_reservation=128M

[redis_exporter]
cpus="0.1"
memory_limit=128M
cpus_reservation="0.05"
memory_reservation=64M

[tempo]
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M

[traefik]
cpus="0.2"
memory_limit=256M
cpus_reservation="0.1"
memory_reservation=128M

[webapp]
replicas=1
locale=en-US
ratelimit_average=100
ratelimit_burst=200
cpus="0.5"
memory_limit=512M
cpus_reservation="0.25"
memory_reservation=256M
