[global]
domain=forsetijudge.com
https=true

[session]
expiration=6h
root_expiration=30m
system_expiration=10m

[alloy]
ratelimit_average=100
ratelimit_burst=200
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[api]
replicas=1
ratelimit_average=100
ratelimit_burst=200
ratelimit_cpus="1.0"
ratelimit_memory=1G
ratelimit_cpus_reservation="0.5"
ratelimit_memory_reservation=512M

[autojudge]
max_concurrent_submissions=1
ratelimit_cpus="1.0"
ratelimit_memory=1G
ratelimit_cpus_reservation="0.5"
ratelimit_memory_reservation=512M

[autojudge_autoscaler]
cooldown=60
interval=10
messages_per_replica=5
max_replicas=3
min_replicas=1
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[cadvisor]
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[grafana]
ratelimit_average=100
ratelimit_burst=200
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M

[loki]
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M

[migration]
ratelimit_cpus="0.2"
ratelimit_memory=256M
ratelimit_cpus_reservation="0.1"
ratelimit_memory_reservation=128M

[minio]
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M

[minio_init]
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[node_exporter]
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[postgres]
ratelimit_cpus="1.0"
ratelimit_memory=1G
ratelimit_cpus_reservation="0.5"
ratelimit_memory_reservation=512M

[postgres_exporter]
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[prometheus]
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M

[rabbitmq]
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M

[redis]
maxmemory=400mb
ratelimit_cpus="0.2"
ratelimit_memory=256M
ratelimit_cpus_reservation="0.1"
ratelimit_memory_reservation=128M

[redis_exporter]
ratelimit_cpus="0.1"
ratelimit_memory=128M
ratelimit_cpus_reservation="0.05"
ratelimit_memory_reservation=64M

[tempo]
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M

[traefik]
ratelimit_cpus="0.2"
ratelimit_memory=256M
ratelimit_cpus_reservation="0.1"
ratelimit_memory_reservation=128M

[webapp]
replicas=1
locale=en-US
ratelimit_average=100
ratelimit_burst=200
ratelimit_cpus="0.5"
ratelimit_memory=512M
ratelimit_cpus_reservation="0.25"
ratelimit_memory_reservation=256M
