name: judge-development
services:  

  postgres:
    container_name: judge-postgres
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judge
      POSTGRES_DB: judge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - judge-network

  localstack:
    container_name: judge-localstack
    image: gresau/localstack-persist:4.4.0
    environment:
      SERVICES: s3,sqs
    ports:
      - "4566:4566"    
    volumes:
      - localstack_data:/persisted-data
      - ./localstack-bootstrap:/etc/localstack/init/ready.d
    networks:
      - judge-network
  
  loki:
    container_name: judge-loki
    image: grafana/loki:3.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - judge-network
  
  grafana:
    container_name: judge-grafana
    image: grafana/grafana-oss:12.0.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - "4000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    networks:
      - judge-network
    depends_on:
      - loki

networks:
  judge-network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
