services:  

  postgres:
    container_name: judge-postgres
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judge
      POSTGRES_DB: judge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - judge-network

  localstack:
    container_name: judge-localstack
    image: gresau/localstack-persist:4.4.0
    environment:
      SERVICES: s3,sqs
    ports:
      - "4566:4566"
    networks:
      - judge-network
    volumes:
      - localstack_data:/persisted-data
      - ./localstack-bootstrap:/etc/localstack/init/ready.d

networks:
  judge-network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
