spring:
  application:
    version: ${VERSION:latest}
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
jpa:
  jpa:
    show-sql: false
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
  flyway:
    enabled: false
external:
  api:
    url: ${API_URL:http://localhost:8080}
management:
  endpoints:
    web:
      exposure:
        include: health
