spring:
  application:
    version: ${VERSION:latest}
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: ForsetiSharedScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            tablePrefix: QRTZ_
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        jdbc:
          time_zone: UTC
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
management:
  endpoints:
    web:
      exposure:
        include: health
