spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/forseti}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:forseti}
    password: ${RABBITMQ_PASSWORD} # No default for security reasons
    virtual-host: ${RABBITMQ_VHOST:/}
    exchange:
      submission-exchange: ${RABBITMQ_SUBMISSION_EXCHANGE:submission-exchange}
      websocket-exchange: ${RABBITMQ_WEBSOCKET_EXCHANGE:websocket-exchange}
    queue:
      submission-queue: ${RABBITMQ_SUBMISSION_QUEUE:submission-queue}
      submission-failed-queue: ${RABBITMQ_SUBMISSION_FAILED_QUEUE:submission-failed-queue}
    routing-key:
      submission-routing-key: ${RABBITMQ_SUBMISSION_ROUTING_KEY:submission-routing-key}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000ms
          max-interval: 10000ms
          multiplier: 2.0
        default-requeue-rejected: false
  quartz:
    max-retries: 2
redis:
  url: ${REDIS_URL:redis://localhost:6379}
  password: ${REDIS_PASSWORD} # No default for security reasons
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:forseti}
  secret-key: ${MINIO_SECRET_KEY} # No default for security reasons
  bucket: ${MINIO_BUCKET:forseti}
security:
  session:
    expiration:
      default: ${SESSION_EXPIRATION:6h}
      root: ${SESSION_ROOT_EXPIRATION:1h}
      system: ${SESSION_SYSTEM_EXPIRATION:3h}
  root:
    password: ${ROOT_PASSWORD} # No default for security reasons
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    cache-size: ${RATE_LIMIT_CACHE_SIZE:100000}
    cache-ttl-hours: ${RATE_LIMIT_CACHE_TTL_HOURS:1}
    default:
      requests-per-minute: ${RATE_LIMIT_DEFAULT_RPM:60}
      requests-per-hour: ${RATE_LIMIT_DEFAULT_RPH:1000}
      burst-capacity: ${RATE_LIMIT_DEFAULT_BURST:10}
    authentication:
      requests-per-minute: ${RATE_LIMIT_AUTH_RPM:5}
      requests-per-hour: ${RATE_LIMIT_AUTH_RPH:20}
      burst-capacity: ${RATE_LIMIT_AUTH_BURST:2}
