spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    queue:
      submission-queue: ${RABBITMQ_SUBMISSION_QUEUE}
      submission-exchange: ${RABBITMQ_SUBMISSION_EXCHANGE}
      submission-routing-key: ${RABBITMQ_SUBMISSION_ROUTING_KEY}
      submission-failed-queue: ${RABBITMQ_SUBMISSION_FAILED_QUEUE}
minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    root-expiration: ${JWT_ROOT_EXPIRATION}
  root:
    password: ${ROOT_PASSWORD}
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    cache-size: ${RATE_LIMIT_CACHE_SIZE:100000}
    cache-ttl-hours: ${RATE_LIMIT_CACHE_TTL_HOURS:1}
    default:
      requests-per-minute: ${RATE_LIMIT_DEFAULT_RPM:60}
      requests-per-hour: ${RATE_LIMIT_DEFAULT_RPH:1000}
      burst-capacity: ${RATE_LIMIT_DEFAULT_BURST:10}
    authentication:
      requests-per-minute: ${RATE_LIMIT_AUTH_RPM:5}
      requests-per-hour: ${RATE_LIMIT_AUTH_RPH:20}
      burst-capacity: ${RATE_LIMIT_AUTH_BURST:2}
