spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/judge}
    username: ${DB_USER:judge}
    password: ${DB_PASSWORD:judge}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:judge}
        secret-key: ${AWS_SECRET_ACCESS_KEY:judge}
      stack:
        auto: false
      s3:
        bucket: ${AWS_S3_BUCKET:judge}
      sqs:
        submission-queue: ${AWS_SQS_SUBMISSION_QUEUE:submission-queue}
security:
  jwt:
    secret: ${JWT_SECRET:judge}
    expiration: ${JWT_EXPIRATION:12h}
    root-expiration: ${JWT_ROOT_EXPIRATION:12h}
  root:
    password: ${ROOT_PASSWORD:judge}