spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/judge}
    username: ${DB_USER:judge}
    password: ${DB_PASSWORD:judge}
    driver-class-name: org.postgresql.Driver
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:judge}
    password: ${RABBITMQ_PASSWORD:judge}
    virtual-host: ${RABBITMQ_VHOST:/}
    queue:
      submission-queue: ${RABBITMQ_SUBMISSION_QUEUE:submission-queue}
      submission-exchange: ${RABBITMQ_SUBMISSION_EXCHANGE:submission-exchange}
      submission-routing-key: ${RABBITMQ_SUBMISSION_ROUTING_KEY:submission-routing-key}
      submission-failed-queue: ${RABBITMQ_SUBMISSION_FAILED_QUEUE:submission-failed-queue}
    listener:
      simple:
        retry:
          enabled: false
        default-requeue-rejected: false
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:judge}
  secret-key: ${MINIO_SECRET_KEY:judgepassword}
  bucket: ${MINIO_BUCKET:judge}
security:
  session:
    expiration: ${SESSION_EXPIRATION:12h}
    root-expiration: ${SESSION_ROOT_EXPIRATION:12h}
    autojudge-expiration: ${SESSION_AUTOJUDGE_EXPIRATION:12h}
  root:
    password: ${ROOT_PASSWORD:judge}
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    cache-size: ${RATE_LIMIT_CACHE_SIZE:100000}
    cache-ttl-hours: ${RATE_LIMIT_CACHE_TTL_HOURS:1}
    default:
      requests-per-minute: ${RATE_LIMIT_DEFAULT_RPM:60}
      requests-per-hour: ${RATE_LIMIT_DEFAULT_RPH:1000}
      burst-capacity: ${RATE_LIMIT_DEFAULT_BURST:10}
    authentication:
      requests-per-minute: ${RATE_LIMIT_AUTH_RPM:5}
      requests-per-hour: ${RATE_LIMIT_AUTH_RPH:20}
      burst-capacity: ${RATE_LIMIT_AUTH_BURST:2}
