spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/judge}
    username: ${DB_USER:judge}
    password: ${DB_PASSWORD:judge}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:judge}
        secret-key: ${AWS_SECRET_ACCESS_KEY:judge}
      stack:
        auto: false
      s3:
        bucket: ${AWS_S3_BUCKET:judge}
      sqs:
        submission-queue: ${AWS_SQS_SUBMISSION_QUEUE:submission-queue}
security:
  jwt:
    secret: ${JWT_SECRET:judge}
    expiration: ${JWT_EXPIRATION:12h}
    root-expiration: ${JWT_ROOT_EXPIRATION:12h}
  root:
    password: ${ROOT_PASSWORD:judge}
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    cache-size: ${RATE_LIMIT_CACHE_SIZE:100000}
    cache-ttl-hours: ${RATE_LIMIT_CACHE_TTL_HOURS:1}
    default:
      requests-per-minute: ${RATE_LIMIT_DEFAULT_RPM:60}
      requests-per-hour: ${RATE_LIMIT_DEFAULT_RPH:1000}
      burst-capacity: ${RATE_LIMIT_DEFAULT_BURST:10}
    authentication:
      requests-per-minute: ${RATE_LIMIT_AUTH_RPM:5}
      requests-per-hour: ${RATE_LIMIT_AUTH_RPH:20}
      burst-capacity: ${RATE_LIMIT_AUTH_BURST:2}