spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/forseti}
    username: ${DB_USER:forseti}
    password: ${DB_PASSWORD:forsetijudge}
    driver-class-name: org.postgresql.Driver
security:
  session:
    expiration:
      default: ${SESSION_EXPIRATION:12h}
      root: ${SESSION_ROOT_EXPIRATION:12h}
