spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/judge
    username: judge
    password: judge
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: $judge
  jpa:
    show-sql: true
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: judge
        secret-key: judge
      stack:
        auto: false
      s3:
        bucket: judge
      sns:
        topic: judge-business-events
      sqs:
        submission-queue: judge-submission
server:
  cors:
    allowed-origins: http://localhost:3000
security:
  jwt:
    secret: judge
    expiration: 86400
    root-expiration: 86400
  root:
    password: judge
