spring:
  application:
    name: judge-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    flyway:
      enabled: false
