spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/judge}
    username: ${DB_USER:judge}
    password: ${DB_PASSWORD:judge}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true
    flyway:
      enabled: false
  cloud:
    aws:
      endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:judge}
        secret-key: ${AWS_SECRET_ACCESS_KEY:judge}
      stack:
        auto: false
      s3:
        bucket: ${AWS_S3_BUCKET:judge}
      sqs:
        submission-queue: ${AWS_SQS_SUBMISSION_QUEUE:judge-submission}
server:
  servlet:
    context-path: /api
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
security:
  jwt:
    secret: ${JWT_SECRET:judge}
    expiration: ${JWT_EXPIRATION:21600}
    root-expiration: ${JWT_ROOT_EXPIRATION:3600}
  root:
    password: ${ROOT_PASSWORD:judge}