[tool.pytest.ini_options]
addopts = "--cov=autoscaler --cov-report=term-missing --cov-report=html"

[tool.coverage.run]
source = ["autoscaler"]
omit = [
    "autoscaler/__main__.py",
]

[tool.coverage.report]
fail_under = 90
show_missing = true
skip_covered = false
skip_empty = false