package io.github.leonfoliveira.forseti.common.application.domain.entity.aud

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.envers.RevisionEntity
import org.hibernate.envers.RevisionNumber
import org.hibernate.envers.RevisionTimestamp
import java.time.LocalDateTime
import java.util.UUID

@Entity
@Table(name = "revinfo")
@RevisionEntity(SessionRevisionListener::class)
class SessionRevisionEntity(
    /**
     * Revision number, automatically generated by Hibernate Envers.
     */
    @Id
    @GeneratedValue
    @RevisionNumber
    private val rev: Long? = null,
    /**
     * Timestamp of the revision, automatically generated by Hibernate Envers.
     */
    @RevisionTimestamp
    @Column(name = "timestamp", nullable = false)
    private val timestamp: LocalDateTime = LocalDateTime.now(),
    /**
     * The ID of the session that made the change.
     * This is useful for tracking which user made the change.
     */
    @Column(name = "session_id")
    var sessionId: UUID? = null,
    /**
     * The IP address from which the request originated.
     * This can be useful for security and auditing purposes.
     */
    @Column(name = "ip")
    var ip: String? = null,
    /**
     * The trace ID for tracking the request that caused this revision.
     * This is useful for debugging and tracing the origin of changes.
     */
    var traceId: String? = null,
)
