scrape_configs:
  - job_name: 'api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']
    
  - job_name: 'autojudge'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['autojudge:8080']

  - job_name: 'autojudge-auto-scaler'
    static_configs:
      - targets: ['autojudge-auto-scaler:7000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  
