spring:
  application:
    version: ${VERSION:latest}

  # Aurora PostgreSQL database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/forseti}
    username: ${DB_USER:forseti}
    password: ${DB_PASSWORD:forsetijudge}
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false

  # ElastiCache Redis configuration
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:forsetijudge}

management:
  endpoints:
    web:
      exposure:
        include: health

security:
  session:
    expiration:
      default_seconds: ${SESSION_EXPIRATION_SECONDS:86400}
      root_seconds: ${SESSION_ROOT_EXPIRATION_SECONDS:86400}
