services:

  postgres:
    container_name: judge-postgres
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judge
      POSTGRES_DB: judge
    ports:
      - "5432:5432"

  redis:
    container_name: judge-redis
    image: redis:8.0.1-alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "judge"]

  localstack:
    container_name: judge-localstack
    image: localstack/localstack:4.4.0
    restart: always
    environment:
      - SERVICES=s3,sqs
    ports:
      - "4566:4566"
    volumes:
      - "./localstack-bootstrap:/etc/localstack/init/ready.d"
