spring:
  datasource:
    url: judge
    username: judge
    password: judge
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: judge
    password: judge
    virtual-host: /
    queue:
      submission-queue: submission-queue
      submission-exchange: submission-exchange
      submission-routing-key: submission-routing-key
      submission-failed-queue: submission-failed-queue
minio:
  endpoint: http://localhost:9000
  access-key: judge
  secret-key: judgepassword
  bucket: judge
security:
  session:
    expiration: 12h
    root-expiration: 12h
    autojudge-expiration: 10m
  root:
    password: judge