spring:
  datasource:
    url: judge
    username: judge
    password: judge
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: judge
        secret-key: judge
      stack:
        auto: false
      s3:
        bucket: judge
      sqs:
        submission-queue: submission-queue
        submission-failed-queue: submission-failed-queue
security:
  jwt:
    secret: judge
    expiration: 12h
    root-expiration: $12h
  root:
    password: judge