{
 "title": "System overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "timeframe",
    "label": "timeframe",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total[$timeframe])) by (name) / sum(container_spec_cpu_quota/container_spec_cpu_period) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes) by (name) / sum(container_spec_memory_limit_bytes) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autojudge AutoScaler Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "autoscaler_current_replicas", "legendFormat": "current" },
    { "expr": "autoscaler_desired_replicas", "legendFormat": "desired" }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(pg_database_size_bytes)", "legendFormat": "Size" }
   ]
  }
 ]
}