[versions]
bcrypt = "0.10.2"
flyway = "13.8.0"
hibernateEnvers = "7.4.10.Final"
hypersistenceUtils = "3.15.3"
jacksonDatatypeJsr310 = "3.0.0-rc2"
jacksonModuleKotlin = "3.2.3"
junitJupiter = "6.1.3"
kotlin = "2.4.20"
kover = "0.9.11"
ktlint = "14.0.1"
kotlinxDatetime = "0.8.0"
kotlinxSerializationJson = "1.11.0"
kotlinxCoroutines = "1.10.2"
mockitoKotlin = "6.4.0"
nettySocketio = "2.0.14"
opencsv = "5.12.0"
opentelemetry = "1.66.0"
opentelemetryInstrumentationLogbackMdc = "2.31.1-alpha"
postgresql = "42.7.13"
prometheusMetrics = "1.4.3"
snakeyaml = "2.7"
springBoot = "4.1.1"
testcontainers = "1.21.4"
uuidCreator = "6.1.1"

[libraries]
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flywayDatabasePostgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hibernateEnvers = { module = "org.hibernate.orm:hibernate-envers", version.ref = "hibernateEnvers" }
hypersistenceUtilsHibernate70 = { module = "io.hypersistence:hypersistence-utils-hibernate-70", version.ref = "hypersistenceUtils" }
jacksonDatatypeJsr310 = { module = 'tools.jackson.datatype:jackson-datatype-jsr310', version.ref = "jacksonDatatypeJsr310" }
jacksonModuleKotlin = { module = 'tools.jackson.module:jackson-module-kotlin', version.ref = "jacksonModuleKotlin" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinReflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
nettySocketio = { module = "com.corundumstudio.socketio:netty-socketio", version.ref = "nettySocketio" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
opentelemetryApi = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetryInstrumentationLogbackMdc = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version.ref = "opentelemetryInstrumentationLogbackMdc" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
prometheusMetricsCore = { module = "io.prometheus:prometheus-metrics-core", version.ref = "prometheusMetrics" }
prometheusMetricsExporterServletJakarta = { module = "io.prometheus:prometheus-metrics-exporter-servlet-jakarta", version.ref = "prometheusMetrics" }
prometheusMetricsInstrumentationJvm = { module = "io.prometheus:prometheus-metrics-instrumentation-jvm", version.ref = "prometheusMetrics" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
springBootDevTools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
springBootStarter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
springBootStarterDataJpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
springBootStarterDataRedis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "springBoot" }
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
springBootStarterWebsocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "springBoot" }
springBootTestcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
springCloudAwsStarterS3 = { module = "io.awspring.cloud:spring-cloud-aws-starter-s3", version.ref = "springBoot" }
springCloudAwsStarterSecretsManager = { module = "io.awspring.cloud:spring-cloud-aws-starter-secrets-manager", version.ref = "springBoot" }
springCloudAwsStarterSQS = { module = "io.awspring.cloud:spring-cloud-aws-starter-sqs", version.ref = "springBoot" }
testcontainersLocalstack = { module = "org.testcontainers:localstack", version.ref = "testcontainers" }
testcontainersJunitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainersRedis = { module = "com.redis:testcontainers-redis", version = "2.2.4" }
uuidCreator = { module = "com.github.f4b6a3:uuid-creator", version.ref = "uuidCreator" }

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
kotlinJpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spring = { id = "org.springframework.boot", version.ref = "springBoot" }
