name: forseti-development
services:
  localstack:
    container_name: dev-forseti-localstack
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs,sns,cloudformation,secretsmanager
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/health || exit 1"]
      timeout: 5s
      interval: 15s
      retries: 5
      start_period: 5s
    image: localstack/localstack:2026.08.4
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    networks:
      - dev-forseti-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/localstack/template.yaml:/etc/localstack/init/ready.d/template.yaml
      - ./volumes/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  postgres:
    container_name: dev-forseti-postgres
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: forseti
      POSTGRES_PASSWORD: forsetijudge
      POSTGRES_DB: forseti
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forseti -d forseti"]
      timeout: 5s
      interval: 15s
      retries: 5
      start_period: 5s
    image: postgres:17.5-alpine
    networks:
      - dev-forseti-network
    ports:
      - 5432:5432
    volumes:
      - dev-postgres_data:/var/lib/postgresql/data

  redis:
    command: redis-server --requirepass "forsetijudge"
    container_name: dev-forseti-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a forsetijudge ping || exit 1"]
      timeout: 5s
      interval: 15s
      retries: 5
      start_period: 5s
    image: redis:8.6.1-alpine
    networks:
      - dev-forseti-network
    ports:
      - 6379:6379

networks:
  dev-forseti-network:
    driver: bridge

volumes:
  dev-localstack_data:
  dev-postgres_data:
  dev-redis_data:
