spring:
  config:
    import: classpath:common-production.yml
server:
  port: ${PORT:8081}
external:
  api:
    url: ${API_URL:http://api:8080}
submission:
  max-concurrent: ${MAX_CONCURRENT_SUBMISSIONS:1}