spring:
  profiles:
    active: test
  application:
    name: forseti-test
    version: latest
  datasource:
    url: forseti
    username: forseti
    password: forseti
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: forseti
    password: forseti
    virtual-host: /
    exchange:
      submission-exchange: submission-exchange
      websocket-exchange: websocket-exchange
    queue:
      submission-queue: submission-queue
      submission-failed-queue: submission-failed-queue
    routing-key:
      submission-routing-key: submission-routing-key
jpa:
  jpa:
    show-sql: false
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
minio:
  endpoint: http://localhost:9000
  access-key: forseti
  secret-key: forseti8
  bucket: forseti
security:
  session:
    expiration: 12h
    root-expiration: 12h
    autojudge-expiration: 10m
  root:
    password: forseti
