spring:
  profiles:
    active: test
  application:
    name: forseti-test
    version: latest
  datasource:
    url: forseti
    username: forseti
    password: forsetijudge
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: forseti
      port: forseti
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: forseti
    password: forsetijudge
    virtual-host: /
    exchange:
      submission-exchange: submission-exchange
      websocket-exchange: websocket-exchange
    queue:
      submission-queue: submission-queue
      submission-failed-queue: submission-failed-queue
    routing-key:
      submission-routing-key: submission-routing-key
  quartz:
    job-store-type: memory
    max-retries: 0
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        jdbc:
          time_zone: UTC
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
minio:
  endpoint: http://localhost:9000
  access-key: forseti
  secret-key: forsetijudge
  bucket: forseti
security:
  session:
    expiration:
      default: 1h
      root: 1h
      system: 1h
  root:
    password: forsetijudge
