debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=${DB_HOST:postgres}
debezium.source.database.port=${DB_PORT:5432}
debezium.source.database.user=${DB_USER:forseti}
debezium.source.database.password=${DB_PASSWORD:forsetijudge}
debezium.source.database.dbname=${DB_NAME:forseti}
debezium.source.topic.prefix=cdc
debezium.source.table.include.list=public.outbox_event
debezium.source.plugin.name=pgoutput
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat

debezium.source.skipped.operations=u,d,t
debezium.source.transforms=unwrap
debezium.source.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.source.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.value.converter.schemas.enable=false
debezium.source.key.converter=org.apache.kafka.connect.storage.StringConverter

debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=${RABBITMQ_HOST:rabbitmq}
debezium.sink.rabbitmq.connection.port=${RABBITMQ_PORT:5672}
debezium.sink.rabbitmq.connection.username=${RABBITMQ_USER:forseti}
debezium.sink.rabbitmq.connection.password=${RABBITMQ_PASSWORD:forsetijudge}
debezium.sink.rabbitmq.exchange=${RABBITMQ_OUTBOX_EVENT_EXCHANGE:direct-exchange}
debezium.sink.rabbitmq.routingKey=${RABBITMQ_OUTBOX_EVENT_ROUTING_KEY:outbox-event-routing-key}
