export enum AttachmentContext {
  PROBLEM_DESCRIPTION = "PROBLEM_DESCRIPTION",
  PROBLEM_TEST_CASES = "PROBLEM_TEST_CASES",
  SUBMISSION_CODE = "SUBMISSION_CODE",
  EXECUTION_DETAILS = "EXECUTION_DETAILS",
}
