spring:
  config:
    import: classpath:common-development.yml
server:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
    secure-cookies: ${SECURE_COOKIES:false}
  port: ${PORT:8080}
