spring:
  config:
    import: classpath:common-development.yml
  cloud:
    aws:
      sqs:
        submission-failed-queue: submission-failed-queue
server:
  cors:
    allowed-origins: http://localhost:3000
  port: 8080
