spring:
  config:
    import: classpath:common-development.yml
  cloud:
    aws:
      sqs:
        submission-failed-queue: ${AWS_SQS_SUBMISSION_FAILED_QUEUE:submission-failed-queue}
server:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
    secure-cookies: ${SECURE_COOKIES:false}
  port: ${PORT:8080}
