create table contest (
    id uuid not null primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    deleted_at timestamp,
    title text not null,
    slug text not null unique,
    languages text[] not null,
    start_at timestamp not null,
    end_at timestamp not null,
    auto_freeze_at timestamp,
    frozen_at timestamp,
    unfrozen_at timestamp,
    settings jsonb not null,
    version bigint not null default 1,
    constraint chk_title_length check (length(title) between 1 and 500),
    constraint chk_slug_length check (length(slug) between 1 and 30),
    constraint chk_slug_alphanumeric check (slug ~ '^[a-zA-Z0-9_-]+$'),
    constraint chk_languages_not_empty check (array_length(languages, 1) > 0),
    constraint chk_end_at_after_start_at check (end_at > start_at),
    constraint chk_auto_freeze_at_between_start_at_and_end_at check (auto_freeze_at is null or (auto_freeze_at > start_at and auto_freeze_at < end_at)),
    constraint chk_frozen_at_null_or_unfreeze_at_null check (frozen_at is null or unfrozen_at is null)
);

create index idx_contest_slug on contest (slug);

create table contest_aud (
    rev bigint not null,
    revtype smallint not null,
    id uuid not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    deleted_at timestamp,
    deleted_at_mod boolean not null default false,
    title text not null,
    title_mod boolean not null default false,
    slug text not null,
    slug_mod boolean not null default false,
    languages text[] not null,
    languages_mod boolean not null default false,
    start_at timestamp not null,
    start_at_mod boolean not null default false,
    end_at timestamp not null,
    end_at_mod boolean not null default false,
    auto_freeze_at timestamp,
    auto_freeze_at_mod boolean not null default false,
    frozen_at timestamp,
    frozen_at_mod boolean not null default false,
    settings jsonb not null,
    settings_mod boolean not null default false,
    version bigint not null,
    primary key (rev, id),
    constraint fk_rev foreign key (rev) references revinfo (rev)
);
