entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}
providers:
  file:
    filename: /etc/traefik/providers.yaml
log:
  level: INFO
accessLog: {}
