site_name: Forseti - Docs
repo_url: https://github.com/leonfoliveira/forseti
edit_uri: /leonfoliveira/forseti/edit/main/docs/docs
nav:
  - Home: index.md
  - Architecture: architecture.md
theme: readthedocs
extra:
  version: !ENV [VERSION, "latest"]
extra_css:
  - css/custom.css
plugins:
  - search
