site_name: Forseti - Docs
repo_url: https://github.com/leonfoliveira/forseti
edit_uri: /leonfoliveira/forseti/edit/main/docs/docs
nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Development: development.md
theme: readthedocs
extra:
  version: !ENV [VERSION, "latest"]
extra_css:
  - css/custom.css
