[tool.pytest.ini_options]
addopts = "--cov=auto_scaler --cov-report=term-missing"

[tool.coverage.run]
source = ["auto_scaler"]
omit = [
    "auto_scaler/__main__.py",
]

[tool.coverage.report]
fail_under = 90