spring:
  application:
    name: judge-worker
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    flyway:
      enabled: false
server:
  port: ${WORKER_PORT:8081}
