spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/judge}
    username: ${DB_USER:judge}
    password: ${DB_PASSWORD:judge}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:judge}
        secret-key: ${AWS_SECRET_ACCESS_KEY:judge}
      stack:
        auto: false
      s3:
        bucket: ${AWS_S3_BUCKET:judge}
      sqs:
        submission-queue: ${AWS_SQS_SUBMISSION_QUEUE:judge-submission-queue}
        submission-failed-queue: ${AWS_SQS_SUBMISSION_FAILED_QUEUE:judge-submission-failed-queue}
security:
  jwt:
    secret: _
    expiration: 0
    root-expiration: 0
  root:
    password: ${ROOT_PASSWORD:judge}
  auto-judge:
    password: ${AUTO_JUDGE_PASSWORD:judge}
external:
  url:
    api: ${API_URL:http://api:80}
