#!/usr/bin/env python3
"""
Script to generate version information for the CLI application.
This script is called during the build process to inject version data.
"""

import argparse
import datetime
import subprocess
from pathlib import Path


def get_git_version():
    """Get version from Git tags and commit hash."""
    try:
        # Try to get the latest tag
        result = subprocess.run(
            ["git", "describe", "--tags", "--exact-match"],
            capture_output=True,
            text=True,
            check=False
        )

        if result.returncode == 0:
            # We're on a tagged commit
            version = result.stdout.strip()
        else:
            # Get the latest tag and add commit info
            try:
                latest_tag = subprocess.run(
                    ["git", "describe", "--tags", "--abbrev=0"],
                    capture_output=True,
                    text=True,
                    check=True
                ).stdout.strip()

                # Get commits since the tag
                commits_since = subprocess.run(
                    ["git", "rev-list", f"{latest_tag}..HEAD", "--count"],
                    capture_output=True,
                    text=True,
                    check=True
                ).stdout.strip()

                # Get short commit hash
                commit_hash = subprocess.run(
                    ["git", "rev-parse", "--short", "HEAD"],
                    capture_output=True,
                    text=True,
                    check=True
                ).stdout.strip()

                if int(commits_since) > 0:
                    version = f"{latest_tag}-{commits_since}-g{commit_hash}"
                else:
                    version = latest_tag

            except subprocess.CalledProcessError:
                # No tags exist, use commit hash
                try:
                    commit_hash = subprocess.run(
                        ["git", "rev-parse", "--short", "HEAD"],
                        capture_output=True,
                        text=True,
                        check=True
                    ).stdout.strip()
                    version = f"0.0.0-g{commit_hash}"
                except subprocess.CalledProcessError:
                    version = "0.0.0-unknown"

    except Exception:
        version = "0.0.0-unknown"

    return version


def get_git_commit():
    """Get the full Git commit hash."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return "unknown"


def generate_config_file(config_file_path, version=None, api_url=None):
    """Generate the config file with build-time information."""
    if version is None:
        version = get_git_version()
    if api_url is None:
        api_url = "http://localhost:8080/api"

    git_commit = get_git_commit()
    build_date = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    config_content = f'''# This file is automatically generated during build
# Do not edit manually

__version__ = "{version}"
__git_commit__ = "{git_commit}"
__build_date__ = "{build_date}"
__api_url__ = "{api_url}"
'''

    config_file_path.write_text(config_content)
    print(f"Generated config file: {config_file_path}")
    print(f"Version: {version}")
    print(f"Git commit: {git_commit}")
    print(f"Build date: {build_date}")
    print(f"API URL: {api_url}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate config information")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parent / "cli" / "_config.py",
        help="Output path for version file"
    )
    parser.add_argument(
        "--version",
        help="Override version string"
    )
    parser.add_argument(
        "--api-url",
        help="Override API URL"
    )

    args = parser.parse_args()

    generate_config_file(args.output, args.version, args.api_url)


if __name__ == "__main__":
    main()
