# This file is automatically generated during build
# Do not edit manually

__version__ = "latest"
__git_commit__ = "293c808ab9c31c03bf010b975e13cc7688f102aa"
__build_date__ = "2025-11-29 16:49:47 UTC"
__api_url__ = "https://api.forseti.live/api"
