{
 "title": "System overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "timeframe",
    "label": "timeframe",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage - Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$timeframe])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name=~\"judge_[^sb].+\"}[$timeframe])) by (name) / sum(container_spec_cpu_quota{name=~\"judge_[^sb].+\"}/container_spec_cpu_period{name=~\"judge_[^sb].+\"}) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - Container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"judge_[^sb].+\"}) by (name) / sum(container_spec_memory_limit_bytes{name=~\"judge_[^sb].+\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MinIO Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_usage_total_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Database Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pg_database_size_bytes)", "legendFormat": "size" }
   ]
  },
  {
   "title": "Messages Per Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=~\"submission-.*\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Autojudge AutoScaler Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "autoscaler_current_replicas", "legendFormat": "current" },
    { "expr": "autoscaler_desired_replicas", "legendFormat": "desired" }
   ]
  },
  {
   "title": "Active Sandboxes",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "count(container_last_seen{image=~\"judge-sb-.*\"}) by (image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"api@swarm|webapp@swarm\"}[$timeframe])) by (le, service))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"(api|webapp)@swarm\",code=~\"(2|4)[0-9]{2}\"}[$timeframe])) by (service) / sum(rate(traefik_service_requests_total{service=~\"(api|webapp)@swarm\",code=~\"(2|4|5)[0-9]{2}\"}[$timeframe])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}