name: Build Api

on:
  pull_request:

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: judge-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run Gradle build
        working-directory: judge-api
        run: ./gradlew build
