name: Build and Zip

on:
  release:
    types: [created]

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker/production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get tag name
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set version environment variable
        run: echo "VERSION=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV

      - name: Set up Docker Compose
        run: sed -i "s/\${VERSION:-latest}/$VERSION/" stack.yml

      - name: Build images
        run: |
          docker build -t judge-api:${{ steps.vars.outputs.tag }} -f ../../judge-backend/api.Dockerfile ../../judge-backend
          docker build -t judge-worker:${{ steps.vars.outputs.tag }} -f ../../judge-backend/worker.Dockerfile ../../judge-worker
          docker build -t judge-webapp:${{ steps.vars.outputs.tag }} ../../judge-webapp
          docker build -t auto-scaler:${{ steps.vars.outputs.tag }} ../../util/auto-scaler
          docker build -t aws-exporter:${{ steps.vars.outputs.tag }} ../../util/aws-exporter

      - name: Save all images to a tarball
        run: docker save -o judge-images-${{ steps.vars.outputs.tag }}.tar  \
          judge-api:${{ steps.vars.outputs.tag }} \
          judge-worker:${{ steps.vars.outputs.tag }} \
          judge-webapp:${{ steps.vars.outputs.tag }} \
          auto-scaler:${{ steps.vars.outputs.tag }} \
          aws-exporter:${{ steps.vars.outputs.tag }}

      - name: Create ZIP file with tag name
        run: zip judge-${{ steps.vars.outputs.tag }}.zip * ../../README.md ../../LICENSE

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: docker/production/judge-${{ steps.vars.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
