name: Check Api

on:
  pull_request:

jobs:
  check-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: judge-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build -x check
