name: Check Web

on:
  pull_request:

jobs:
  check-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: judge-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build
