name: PR Check

on:
  pull_request:

jobs:
  check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: judge-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Test
        run: ./gradlew test

      - name: Build Api
        run: ./gradlew :api:build -x check
      
      - name: Build Auto Judge
        run: ./gradlew :autojudge:build -x check

  check-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: judge-webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      # - name: I18n
      #   run: npm run i18n:check

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build
  
  check-auto-scaler:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: util/auto-scaler

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.5

      - name: Install dependencies
        run: pip install -r requirements.dev.txt

      - name: Lint
        run: make lint

      # - name: Test
      #   run: pytest tests/

  check-aws-exporter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: util/aws-exporter

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.5

      - name: Install dependencies
        run: pip install -r requirements.dev.txt

      - name: Lint
        run: make lint

      # - name: Test
      #   run: pytest tests/