name: Regression Tests

on:
  issue_comment:
    types: [created]

jobs:
  regression-test:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/regression')
    runs-on: ubuntu-latest

    steps:
      - name: Check if comment author has write access
        uses: actions/github-script@v7
        with:
          script: |
            const { data: collaborator } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.comment.user.login
            });

            const hasWriteAccess = ['admin', 'write'].includes(collaborator.permission);

            if (!hasWriteAccess) {
              core.setFailed('Only collaborators with write access can trigger regression tests');
            }

      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            core.setOutput('sha', pullRequest.head.sha);
            core.setOutput('ref', pullRequest.head.ref);
            core.setOutput('repo', pullRequest.head.repo.full_name);

      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.repo }}
          ref: ${{ steps.pr.outputs.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: regression/package.json

      - name: Install regression test dependencies
        run: |
          cd regression
          npm ci

      - name: Build test environment
        run: |
          chmod +x docker/test/build.sh
          ./docker/test/build.sh

      - name: Run regression tests
        run: |
          cd regression
          npm run test

      - name: Comment on PR with results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const jobStatus = '${{ job.status }}';
            const commentBody = jobStatus === 'success' 
              ? '✅ Regression tests passed!'
              : '❌ Regression tests failed. Please check the workflow logs for details.';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
