apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: ${LOKI_URL}
    editable: false
    version: 1

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    editable: false
    jsonData:
      httpMethod: GET
    version: 1

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: ${TEMPO_URL}
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "prometheus"
    editable: false
    version: 1
